// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: sds.proto

package sdslogic

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Quota struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//  reserved 1;
	Rid   string `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Owner string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Size  int32  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Quota) Reset() {
	*x = Quota{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sds_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quota) ProtoMessage() {}

func (x *Quota) ProtoReflect() protoreflect.Message {
	mi := &file_sds_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quota.ProtoReflect.Descriptor instead.
func (*Quota) Descriptor() ([]byte, []int) {
	return file_sds_proto_rawDescGZIP(), []int{0}
}

func (x *Quota) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quota) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *Quota) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Quota) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type QuotaId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rid string `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
}

func (x *QuotaId) Reset() {
	*x = QuotaId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sds_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuotaId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaId) ProtoMessage() {}

func (x *QuotaId) ProtoReflect() protoreflect.Message {
	mi := &file_sds_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaId.ProtoReflect.Descriptor instead.
func (*QuotaId) Descriptor() ([]byte, []int) {
	return file_sds_proto_rawDescGZIP(), []int{1}
}

func (x *QuotaId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuotaId) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type QuotasSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid    string   `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Quotas []*Quota `protobuf:"bytes,3,rep,name=quotas,proto3" json:"quotas,omitempty"`
}

func (x *QuotasSummary) Reset() {
	*x = QuotasSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sds_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuotasSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotasSummary) ProtoMessage() {}

func (x *QuotasSummary) ProtoReflect() protoreflect.Message {
	mi := &file_sds_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotasSummary.ProtoReflect.Descriptor instead.
func (*QuotasSummary) Descriptor() ([]byte, []int) {
	return file_sds_proto_rawDescGZIP(), []int{2}
}

func (x *QuotasSummary) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *QuotasSummary) GetQuotas() []*Quota {
	if x != nil {
		return x.Quotas
	}
	return nil
}

type UtilisationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid string `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
}

func (x *UtilisationRequest) Reset() {
	*x = UtilisationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sds_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UtilisationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtilisationRequest) ProtoMessage() {}

func (x *UtilisationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sds_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtilisationRequest.ProtoReflect.Descriptor instead.
func (*UtilisationRequest) Descriptor() ([]byte, []int) {
	return file_sds_proto_rawDescGZIP(), []int{3}
}

func (x *UtilisationRequest) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type UtilisationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid     string `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Limit   string `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Current string `protobuf:"bytes,4,opt,name=current,proto3" json:"current,omitempty"`
}

func (x *UtilisationResponse) Reset() {
	*x = UtilisationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sds_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UtilisationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtilisationResponse) ProtoMessage() {}

func (x *UtilisationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sds_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtilisationResponse.ProtoReflect.Descriptor instead.
func (*UtilisationResponse) Descriptor() ([]byte, []int) {
	return file_sds_proto_rawDescGZIP(), []int{4}
}

func (x *UtilisationResponse) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *UtilisationResponse) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

func (x *UtilisationResponse) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

var File_sds_proto protoreflect.FileDescriptor

var file_sds_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x64, 0x73,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x22, 0x53, 0x0a, 0x05, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x2b, 0x0a, 0x07, 0x51, 0x75,
	0x6f, 0x74, 0x61, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x72, 0x69, 0x64, 0x22, 0x50, 0x0a, 0x0d, 0x51, 0x75, 0x6f, 0x74, 0x61,
	0x73, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x71, 0x75,
	0x6f, 0x74, 0x61, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x64, 0x73,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x06, 0x71, 0x75, 0x6f,
	0x74, 0x61, 0x73, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x22, 0x2c, 0x0a, 0x12, 0x55, 0x74, 0x69,
	0x6c, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x69,
	0x64, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x22, 0x5d, 0x0a, 0x13, 0x55, 0x74, 0x69, 0x6c, 0x69,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x32, 0xcf, 0x01, 0x0a, 0x0a, 0x55, 0x74, 0x69, 0x6c, 0x69,
	0x73, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x74, 0x69, 0x6c,
	0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x73, 0x64, 0x73, 0x6c, 0x6f, 0x67,
	0x69, 0x63, 0x2e, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x64, 0x73, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x2e, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x12, 0x0f, 0x2e, 0x73, 0x64, 0x73, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x51, 0x75,
	0x6f, 0x74, 0x61, 0x1a, 0x17, 0x2e, 0x73, 0x64, 0x73, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x73, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x00, 0x12, 0x38,
	0x0a, 0x08, 0x44, 0x65, 0x6c, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x11, 0x2e, 0x73, 0x64, 0x73,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x49, 0x64, 0x1a, 0x17, 0x2e,
	0x73, 0x64, 0x73, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x73, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x68, 0x61, 0x6e, 0x6e, 0x7a, 0x2f, 0x73, 0x75,
	0x70, 0x65, 0x72, 0x2d, 0x64, 0x75, 0x70, 0x65, 0x72, 0x2d, 0x73, 0x70, 0x6f, 0x72, 0x6b, 0x2f,
	0x73, 0x64, 0x73, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sds_proto_rawDescOnce sync.Once
	file_sds_proto_rawDescData = file_sds_proto_rawDesc
)

func file_sds_proto_rawDescGZIP() []byte {
	file_sds_proto_rawDescOnce.Do(func() {
		file_sds_proto_rawDescData = protoimpl.X.CompressGZIP(file_sds_proto_rawDescData)
	})
	return file_sds_proto_rawDescData
}

var file_sds_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sds_proto_goTypes = []interface{}{
	(*Quota)(nil),               // 0: sdslogic.Quota
	(*QuotaId)(nil),             // 1: sdslogic.QuotaId
	(*QuotasSummary)(nil),       // 2: sdslogic.QuotasSummary
	(*UtilisationRequest)(nil),  // 3: sdslogic.UtilisationRequest
	(*UtilisationResponse)(nil), // 4: sdslogic.UtilisationResponse
}
var file_sds_proto_depIdxs = []int32{
	0, // 0: sdslogic.QuotasSummary.quotas:type_name -> sdslogic.Quota
	3, // 1: sdslogic.Utilisator.GetUtilisation:input_type -> sdslogic.UtilisationRequest
	0, // 2: sdslogic.Utilisator.AddQuota:input_type -> sdslogic.Quota
	1, // 3: sdslogic.Utilisator.DelQuota:input_type -> sdslogic.QuotaId
	4, // 4: sdslogic.Utilisator.GetUtilisation:output_type -> sdslogic.UtilisationResponse
	2, // 5: sdslogic.Utilisator.AddQuota:output_type -> sdslogic.QuotasSummary
	2, // 6: sdslogic.Utilisator.DelQuota:output_type -> sdslogic.QuotasSummary
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sds_proto_init() }
func file_sds_proto_init() {
	if File_sds_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sds_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quota); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sds_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuotaId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sds_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuotasSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sds_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UtilisationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sds_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UtilisationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sds_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sds_proto_goTypes,
		DependencyIndexes: file_sds_proto_depIdxs,
		MessageInfos:      file_sds_proto_msgTypes,
	}.Build()
	File_sds_proto = out.File
	file_sds_proto_rawDesc = nil
	file_sds_proto_goTypes = nil
	file_sds_proto_depIdxs = nil
}
